// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type CancelRunningGroupRequest struct {
	// id of the group
	Group string `pathParam:"style=simple,explode=false,name=group"`
}

func (o *CancelRunningGroupRequest) GetGroup() string {
	if o == nil {
		return ""
	}
	return o.Group
}

type CancelRunningGroupResponse struct {
	// a list of any objects
	CancelRunningGroup *shared.CancelRunningGroup
	ContentType        string
	StatusCode         int
	RawResponse        *http.Response
}

func (o *CancelRunningGroupResponse) GetCancelRunningGroup() *shared.CancelRunningGroup {
	if o == nil {
		return nil
	}
	return o.CancelRunningGroup
}

func (o *CancelRunningGroupResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelRunningGroupResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelRunningGroupResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
