// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cribl/pkg/models/shared"
	"net/http"
)

type CancelJobRequest struct {
	// Job instance id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *CancelJobRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type CancelJobResponse struct {
	ContentType string
	// a list of any objects
	JobCancel   *shared.JobCancel
	StatusCode  int
	RawResponse *http.Response
}

func (o *CancelJobResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CancelJobResponse) GetJobCancel() *shared.JobCancel {
	if o == nil {
		return nil
	}
	return o.JobCancel
}

func (o *CancelJobResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CancelJobResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
