// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type DeleteSearchJobRequest struct {
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteSearchJobRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteSearchJobResponse struct {
	ContentType string
	// a list of SearchJob objects
	SearchJob   *shared.SearchJob
	StatusCode  int
	RawResponse *http.Response
}

func (o *DeleteSearchJobResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteSearchJobResponse) GetSearchJob() *shared.SearchJob {
	if o == nil {
		return nil
	}
	return o.SearchJob
}

func (o *DeleteSearchJobResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteSearchJobResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
