// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cribl/pkg/models/shared"
	"net/http"
)

type GetDatasetProviderTypesResponse struct {
	ContentType string
	// a list of DatasetProviderType objects
	DatasetProviderTypes *shared.DatasetProviderTypes
	StatusCode           int
	RawResponse          *http.Response
}

func (o *GetDatasetProviderTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetDatasetProviderTypesResponse) GetDatasetProviderTypes() *shared.DatasetProviderTypes {
	if o == nil {
		return nil
	}
	return o.DatasetProviderTypes
}

func (o *GetDatasetProviderTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetDatasetProviderTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
