// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type GetEdgeListingRequest struct {
	// Unique ID
	Path string `pathParam:"style=simple,explode=false,name=path"`
}

func (o *GetEdgeListingRequest) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

type GetEdgeListingResponse struct {
	ContentType string
	// a list of FilesystemEntry objects
	FilesystemEntries *shared.FilesystemEntries
	StatusCode        int
	RawResponse       *http.Response
}

func (o *GetEdgeListingResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetEdgeListingResponse) GetFilesystemEntries() *shared.FilesystemEntries {
	if o == nil {
		return nil
	}
	return o.FilesystemEntries
}

func (o *GetEdgeListingResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetEdgeListingResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
