// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cribl/pkg/models/shared"
	"net/http"
)

type GetIDPAuthRequest struct {
	// Authorization Code
	Code  *string `queryParam:"style=form,explode=true,name=code"`
	State *string `queryParam:"style=form,explode=true,name=state"`
}

func (o *GetIDPAuthRequest) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetIDPAuthRequest) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

type GetIDPAuthResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Authorization success
	Success *shared.Success
}

func (o *GetIDPAuthResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetIDPAuthResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetIDPAuthResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetIDPAuthResponse) GetSuccess() *shared.Success {
	if o == nil {
		return nil
	}
	return o.Success
}
