// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cribl/pkg/models/shared"
	"net/http"
)

type GetJobRequest struct {
	// Job instance id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetJobRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetJobResponse struct {
	ContentType string
	// a list of JobInfo objects
	JobInfos    *shared.JobInfos
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetJobResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetJobResponse) GetJobInfos() *shared.JobInfos {
	if o == nil {
		return nil
	}
	return o.JobInfos
}

func (o *GetJobResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetJobResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
