// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type GetSavedJobRequest struct {
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSavedJobRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetSavedJobResponse struct {
	ContentType string
	// a list of SavedJob objects
	SavedJobs   *shared.SavedJobs
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetSavedJobResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSavedJobResponse) GetSavedJobs() *shared.SavedJobs {
	if o == nil {
		return nil
	}
	return o.SavedJobs
}

func (o *GetSavedJobResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSavedJobResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
