// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cribl/pkg/models/shared"
	"net/http"
)

type GetSavedQueriesResponse struct {
	ContentType string
	// a list of SavedQuery objects
	SavedQueries *shared.SavedQueries
	StatusCode   int
	RawResponse  *http.Response
}

func (o *GetSavedQueriesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSavedQueriesResponse) GetSavedQueries() *shared.SavedQueries {
	if o == nil {
		return nil
	}
	return o.SavedQueries
}

func (o *GetSavedQueriesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSavedQueriesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
