// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type GetSearchJobRequest struct {
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSearchJobRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetSearchJobResponse struct {
	ContentType string
	// a list of SearchJob objects
	SearchJob   *shared.SearchJob
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetSearchJobResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSearchJobResponse) GetSearchJob() *shared.SearchJob {
	if o == nil {
		return nil
	}
	return o.SearchJob
}

func (o *GetSearchJobResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSearchJobResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
