// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type ListEdgeHostFilesResponse struct {
	ContentType string
	// a list of EdgeFileInspectResponse objects
	EdgeHostFiles *shared.EdgeHostFiles
	StatusCode    int
	RawResponse   *http.Response
}

func (o *ListEdgeHostFilesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListEdgeHostFilesResponse) GetEdgeHostFiles() *shared.EdgeHostFiles {
	if o == nil {
		return nil
	}
	return o.EdgeHostFiles
}

func (o *ListEdgeHostFilesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListEdgeHostFilesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
