// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type ListProfilersResponse struct {
	ContentType string
	// a list of ProfilerItem objects
	ProfilerItems *shared.ProfilerItems
	StatusCode    int
	RawResponse   *http.Response
}

func (o *ListProfilersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListProfilersResponse) GetProfilerItems() *shared.ProfilerItems {
	if o == nil {
		return nil
	}
	return o.ProfilerItems
}

func (o *ListProfilersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListProfilersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
