// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type ListSearchLogsRequest struct {
	// search job id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ListSearchLogsRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ListSearchLogsResponse struct {
	ContentType string
	// a list of string objects
	SearchLogs  *shared.SearchLogs
	StatusCode  int
	RawResponse *http.Response
}

func (o *ListSearchLogsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListSearchLogsResponse) GetSearchLogs() *shared.SearchLogs {
	if o == nil {
		return nil
	}
	return o.SearchLogs
}

func (o *ListSearchLogsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListSearchLogsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
