// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type ListProcessRunningDetailResponse struct {
	ContentType string
	// a list of Process objects
	Processes   *shared.Processes
	StatusCode  int
	RawResponse *http.Response
}

func (o *ListProcessRunningDetailResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListProcessRunningDetailResponse) GetProcesses() *shared.Processes {
	if o == nil {
		return nil
	}
	return o.Processes
}

func (o *ListProcessRunningDetailResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListProcessRunningDetailResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
