// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type ListExecutorObjectResponse struct {
	ContentType string
	// a list of Executor objects
	Executors   *shared.Executors
	StatusCode  int
	RawResponse *http.Response
}

func (o *ListExecutorObjectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListExecutorObjectResponse) GetExecutors() *shared.Executors {
	if o == nil {
		return nil
	}
	return o.Executors
}

func (o *ListExecutorObjectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListExecutorObjectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
