// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type ListCriblVersionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// a list of UpgradeResult objects
	UpgradeResults *shared.UpgradeResults
}

func (o *ListCriblVersionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListCriblVersionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListCriblVersionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListCriblVersionResponse) GetUpgradeResults() *shared.UpgradeResults {
	if o == nil {
		return nil
	}
	return o.UpgradeResults
}
