// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type ListLookupsResponse struct {
	ContentType string
	// a list of LookupFile objects
	LookupFiles *shared.LookupFiles
	StatusCode  int
	RawResponse *http.Response
}

func (o *ListLookupsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListLookupsResponse) GetLookupFiles() *shared.LookupFiles {
	if o == nil {
		return nil
	}
	return o.LookupFiles
}

func (o *ListLookupsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListLookupsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
