// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type ListLicenseUsageMetricsResponse struct {
	ContentType string
	// a list of DailyUsageMetrics objects
	DailyMetrics *shared.DailyMetrics
	StatusCode   int
	RawResponse  *http.Response
}

func (o *ListLicenseUsageMetricsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListLicenseUsageMetricsResponse) GetDailyMetrics() *shared.DailyMetrics {
	if o == nil {
		return nil
	}
	return o.DailyMetrics
}

func (o *ListLicenseUsageMetricsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListLicenseUsageMetricsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
