// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type LogoutRedirectUserAuthResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// SLO redirect info
	Success *shared.Success
}

func (o *LogoutRedirectUserAuthResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LogoutRedirectUserAuthResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LogoutRedirectUserAuthResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *LogoutRedirectUserAuthResponse) GetSuccess() *shared.Success {
	if o == nil {
		return nil
	}
	return o.Success
}
