// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type PostSampleOutputRequest struct {
	// OutputTestRequest object
	OutputTestRequest *shared.OutputTestRequest `request:"mediaType=application/json"`
	// Output Id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *PostSampleOutputRequest) GetOutputTestRequest() *shared.OutputTestRequest {
	if o == nil {
		return nil
	}
	return o.OutputTestRequest
}

func (o *PostSampleOutputRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type PostSampleOutputResponse struct {
	ContentType string
	// a list of OutputTestResponse objects
	OutputTestResponses *shared.OutputTestResponses
	StatusCode          int
	RawResponse         *http.Response
}

func (o *PostSampleOutputResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostSampleOutputResponse) GetOutputTestResponses() *shared.OutputTestResponses {
	if o == nil {
		return nil
	}
	return o.OutputTestResponses
}

func (o *PostSampleOutputResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostSampleOutputResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
