// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/cribl-go/pkg/models/shared"
	"net/http"
)

type UpdateAppscopeLibEntryRequest struct {
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// AppscopeLibEntry object to be updated
	AppscopeLibEntry *shared.AppscopeLibEntry `request:"mediaType=application/json"`
}

func (o *UpdateAppscopeLibEntryRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateAppscopeLibEntryRequest) GetAppscopeLibEntry() *shared.AppscopeLibEntry {
	if o == nil {
		return nil
	}
	return o.AppscopeLibEntry
}

type UpdateAppscopeLibEntryResponse struct {
	// a list of AppscopeLibEntry objects
	AppscopeLibEntry *shared.AppscopeLibEntry
	ContentType      string
	StatusCode       int
	RawResponse      *http.Response
}

func (o *UpdateAppscopeLibEntryResponse) GetAppscopeLibEntry() *shared.AppscopeLibEntry {
	if o == nil {
		return nil
	}
	return o.AppscopeLibEntry
}

func (o *UpdateAppscopeLibEntryResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateAppscopeLibEntryResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateAppscopeLibEntryResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
