// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// Success - Authorization success
type Success struct {
	// Success message
	Message *string `json:"message,omitempty"`
}

var _ error = &Success{}

func (e *Success) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
