// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppScopeLibEntries - a list of AppscopeLibEntry objects
type AppScopeLibEntries struct {
	// number of items present in the items array
	Count *int64             `json:"count,omitempty"`
	Items []AppscopeLibEntry `json:"items,omitempty"`
}

func (o *AppScopeLibEntries) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *AppScopeLibEntries) GetItems() []AppscopeLibEntry {
	if o == nil {
		return nil
	}
	return o.Items
}
