// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BulletinMessages - a list of BulletinMessage objects
type BulletinMessages struct {
	// number of items present in the items array
	Count *int64            `json:"count,omitempty"`
	Items []BulletinMessage `json:"items,omitempty"`
}

func (o *BulletinMessages) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *BulletinMessages) GetItems() []BulletinMessage {
	if o == nil {
		return nil
	}
	return o.Items
}
