// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ChangelogStateses - a list of ChangelogState objects
type ChangelogStateses struct {
	// number of items present in the items array
	Count *int64 `json:"count,omitempty"`
}

func (o *ChangelogStateses) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}
