// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CluiItem struct {
	Category CluiCategory `json:"category"`
	GroupID  *string      `json:"groupId,omitempty"`
	ID       *string      `json:"id,omitempty"`
	Name     *string      `json:"name,omitempty"`
	PackID   *string      `json:"packId,omitempty"`
	SubType  *string      `json:"subType,omitempty"`
	Type     CluiType     `json:"type"`
}

func (o *CluiItem) GetCategory() CluiCategory {
	if o == nil {
		return CluiCategory("")
	}
	return o.Category
}

func (o *CluiItem) GetGroupID() *string {
	if o == nil {
		return nil
	}
	return o.GroupID
}

func (o *CluiItem) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CluiItem) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CluiItem) GetPackID() *string {
	if o == nil {
		return nil
	}
	return o.PackID
}

func (o *CluiItem) GetSubType() *string {
	if o == nil {
		return nil
	}
	return o.SubType
}

func (o *CluiItem) GetType() CluiType {
	if o == nil {
		return CluiType("")
	}
	return o.Type
}
