// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ColumnSortSettings struct {
	Sort interface{} `json:"sort"`
}

func (o *ColumnSortSettings) GetSort() interface{} {
	if o == nil {
		return nil
	}
	return o.Sort
}
