// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ColumnFilterSettings struct {
	Contains interface{} `json:"contains"`
}

func (o *ColumnFilterSettings) GetContains() interface{} {
	if o == nil {
		return nil
	}
	return o.Contains
}
