// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CrudEntityBase - CrudEntityBase object
type CrudEntityBase struct {
	ID string `json:"id"`
}

func (o *CrudEntityBase) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
