// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DockerInfo struct {
	Config          map[string]interface{} `json:"Config,omitempty"`
	GraphDriver     *DockerGraphDriver     `json:"GraphDriver,omitempty"`
	LogPath         *string                `json:"LogPath,omitempty"`
	Mounts          []DockerMount          `json:"Mounts,omitempty"`
	NetworkSettings map[string]interface{} `json:"NetworkSettings,omitempty"`
	Path            *string                `json:"Path,omitempty"`
	State           map[string]interface{} `json:"State,omitempty"`
	Stats           map[string]interface{} `json:"Stats,omitempty"`
}

func (o *DockerInfo) GetConfig() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Config
}

func (o *DockerInfo) GetGraphDriver() *DockerGraphDriver {
	if o == nil {
		return nil
	}
	return o.GraphDriver
}

func (o *DockerInfo) GetLogPath() *string {
	if o == nil {
		return nil
	}
	return o.LogPath
}

func (o *DockerInfo) GetMounts() []DockerMount {
	if o == nil {
		return nil
	}
	return o.Mounts
}

func (o *DockerInfo) GetNetworkSettings() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.NetworkSettings
}

func (o *DockerInfo) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *DockerInfo) GetState() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *DockerInfo) GetStats() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Stats
}
