// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FieldSummaries - FieldSummaries object
type FieldSummaries struct {
	Fields          []Field `json:"fields"`
	Partial         *bool   `json:"partial,omitempty"`
	TotalEventCount int64   `json:"totalEventCount"`
}

func (o *FieldSummaries) GetFields() []Field {
	if o == nil {
		return []Field{}
	}
	return o.Fields
}

func (o *FieldSummaries) GetPartial() *bool {
	if o == nil {
		return nil
	}
	return o.Partial
}

func (o *FieldSummaries) GetTotalEventCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalEventCount
}
