// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MasterWorkerEntries - a list of MasterWorkerEntry objects
type MasterWorkerEntries struct {
	// number of items present in the items array
	Count *int64              `json:"count,omitempty"`
	Items []MasterWorkerEntry `json:"items,omitempty"`
}

func (o *MasterWorkerEntries) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *MasterWorkerEntries) GetItems() []MasterWorkerEntry {
	if o == nil {
		return nil
	}
	return o.Items
}
