// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PackInfoTags struct {
	DataType   []string `json:"dataType"`
	Domain     []string `json:"domain"`
	Streamtags []string `json:"streamtags"`
	Technology []string `json:"technology"`
}

func (o *PackInfoTags) GetDataType() []string {
	if o == nil {
		return []string{}
	}
	return o.DataType
}

func (o *PackInfoTags) GetDomain() []string {
	if o == nil {
		return []string{}
	}
	return o.Domain
}

func (o *PackInfoTags) GetStreamtags() []string {
	if o == nil {
		return []string{}
	}
	return o.Streamtags
}

func (o *PackInfoTags) GetTechnology() []string {
	if o == nil {
		return []string{}
	}
	return o.Technology
}

type PackInfo struct {
	Author              *string                `json:"author,omitempty"`
	Description         *string                `json:"description,omitempty"`
	DisplayName         *string                `json:"displayName,omitempty"`
	ID                  string                 `json:"id"`
	IsDisabled          *bool                  `json:"isDisabled,omitempty"`
	MinLogStreamVersion *string                `json:"minLogStreamVersion,omitempty"`
	Settings            map[string]interface{} `json:"settings,omitempty"`
	Source              string                 `json:"source"`
	Spec                *string                `json:"spec,omitempty"`
	Tags                *PackInfoTags          `json:"tags,omitempty"`
	Version             *string                `json:"version,omitempty"`
}

func (o *PackInfo) GetAuthor() *string {
	if o == nil {
		return nil
	}
	return o.Author
}

func (o *PackInfo) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *PackInfo) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *PackInfo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PackInfo) GetIsDisabled() *bool {
	if o == nil {
		return nil
	}
	return o.IsDisabled
}

func (o *PackInfo) GetMinLogStreamVersion() *string {
	if o == nil {
		return nil
	}
	return o.MinLogStreamVersion
}

func (o *PackInfo) GetSettings() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Settings
}

func (o *PackInfo) GetSource() string {
	if o == nil {
		return ""
	}
	return o.Source
}

func (o *PackInfo) GetSpec() *string {
	if o == nil {
		return nil
	}
	return o.Spec
}

func (o *PackInfo) GetTags() *PackInfoTags {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *PackInfo) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}
