// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SavedJobCollectionCollectorCollectorSpecificSettings struct {
}

type SavedJobCollectionCollector struct {
	Conf SavedJobCollectionCollectorCollectorSpecificSettings `json:"conf"`
	// If set to Yes, the collector will delete any files that it collects (where applicable).
	Destructive *bool `json:"destructive,omitempty"`
	// The type of collector to run.
	Type string `json:"type"`
}

func (o *SavedJobCollectionCollector) GetConf() SavedJobCollectionCollectorCollectorSpecificSettings {
	if o == nil {
		return SavedJobCollectionCollectorCollectorSpecificSettings{}
	}
	return o.Conf
}

func (o *SavedJobCollectionCollector) GetDestructive() *bool {
	if o == nil {
		return nil
	}
	return o.Destructive
}

func (o *SavedJobCollectionCollector) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}

type SavedJobCollectionInputMetadata struct {
	// Field name
	Name string `json:"name"`
	// JavaScript expression to compute field's value, enclosed in quotes or backticks. (Can evaluate to a constant.)
	Value string `json:"value"`
}

func (o *SavedJobCollectionInputMetadata) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SavedJobCollectionInputMetadata) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}

type SavedJobCollectionInputPreprocess struct {
	// Arguments
	Args []string `json:"args,omitempty"`
	// Command to feed the data through (via stdin) and process its output (stdout)
	Command *string `json:"command,omitempty"`
	// Enable Custom Command
	Disabled bool `json:"disabled"`
}

func (o *SavedJobCollectionInputPreprocess) GetArgs() []string {
	if o == nil {
		return nil
	}
	return o.Args
}

func (o *SavedJobCollectionInputPreprocess) GetCommand() *string {
	if o == nil {
		return nil
	}
	return o.Command
}

func (o *SavedJobCollectionInputPreprocess) GetDisabled() bool {
	if o == nil {
		return false
	}
	return o.Disabled
}

type SavedJobCollectionInputType string

const (
	SavedJobCollectionInputTypeCollection SavedJobCollectionInputType = "collection"
)

func (e SavedJobCollectionInputType) ToPointer() *SavedJobCollectionInputType {
	return &e
}

func (e *SavedJobCollectionInputType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "collection":
		*e = SavedJobCollectionInputType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SavedJobCollectionInputType: %v", v)
	}
}

type SavedJobCollectionInput struct {
	// A list of event breaking rulesets that will be applied, in order, to the input data stream.
	BreakerRulesets []string `json:"breakerRulesets,omitempty"`
	// Fields to add to events from this input.
	Metadata []SavedJobCollectionInputMetadata `json:"metadata,omitempty"`
	// Destination to send results to.
	Output *string `json:"output,omitempty"`
	// Pipeline to process results.
	Pipeline   *string                            `json:"pipeline,omitempty"`
	Preprocess *SavedJobCollectionInputPreprocess `json:"preprocess,omitempty"`
	// If set to Yes, events will be sent to normal routing and event processing. Set to No if you want to select a specific Pipeline/Destination combination.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// The amount of time (in milliseconds) the Event Breaker will wait for new data to be sent to a specific channel, before flushing the data stream out, as-is, to the Pipelines.
	StaleChannelFlushMs *int64 `json:"staleChannelFlushMs,omitempty"`
	// Rate (in bytes per second) to throttle while writing to an output. Also takes values with multiple-byte units, such as KB, MB, GB, etc. (E.g., 42 MB.) Default value of 0 specifies no throttling.
	ThrottleRatePerSec *string                      `json:"throttleRatePerSec,omitempty"`
	Type               *SavedJobCollectionInputType `json:"type,omitempty"`
}

func (o *SavedJobCollectionInput) GetBreakerRulesets() []string {
	if o == nil {
		return nil
	}
	return o.BreakerRulesets
}

func (o *SavedJobCollectionInput) GetMetadata() []SavedJobCollectionInputMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *SavedJobCollectionInput) GetOutput() *string {
	if o == nil {
		return nil
	}
	return o.Output
}

func (o *SavedJobCollectionInput) GetPipeline() *string {
	if o == nil {
		return nil
	}
	return o.Pipeline
}

func (o *SavedJobCollectionInput) GetPreprocess() *SavedJobCollectionInputPreprocess {
	if o == nil {
		return nil
	}
	return o.Preprocess
}

func (o *SavedJobCollectionInput) GetSendToRoutes() *bool {
	if o == nil {
		return nil
	}
	return o.SendToRoutes
}

func (o *SavedJobCollectionInput) GetStaleChannelFlushMs() *int64 {
	if o == nil {
		return nil
	}
	return o.StaleChannelFlushMs
}

func (o *SavedJobCollectionInput) GetThrottleRatePerSec() *string {
	if o == nil {
		return nil
	}
	return o.ThrottleRatePerSec
}

func (o *SavedJobCollectionInput) GetType() *SavedJobCollectionInputType {
	if o == nil {
		return nil
	}
	return o.Type
}

// SavedJobCollectionScheduleRunSettingsLogLevel - Level at which to set task logging.
type SavedJobCollectionScheduleRunSettingsLogLevel string

const (
	SavedJobCollectionScheduleRunSettingsLogLevelError SavedJobCollectionScheduleRunSettingsLogLevel = "error"
	SavedJobCollectionScheduleRunSettingsLogLevelWarn  SavedJobCollectionScheduleRunSettingsLogLevel = "warn"
	SavedJobCollectionScheduleRunSettingsLogLevelInfo  SavedJobCollectionScheduleRunSettingsLogLevel = "info"
	SavedJobCollectionScheduleRunSettingsLogLevelDebug SavedJobCollectionScheduleRunSettingsLogLevel = "debug"
	SavedJobCollectionScheduleRunSettingsLogLevelSilly SavedJobCollectionScheduleRunSettingsLogLevel = "silly"
)

func (e SavedJobCollectionScheduleRunSettingsLogLevel) ToPointer() *SavedJobCollectionScheduleRunSettingsLogLevel {
	return &e
}

func (e *SavedJobCollectionScheduleRunSettingsLogLevel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "error":
		fallthrough
	case "warn":
		fallthrough
	case "info":
		fallthrough
	case "debug":
		fallthrough
	case "silly":
		*e = SavedJobCollectionScheduleRunSettingsLogLevel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SavedJobCollectionScheduleRunSettingsLogLevel: %v", v)
	}
}

type SavedJobCollectionScheduleRunSettings struct {
	// Earliest time, for the given Range Timezone.
	Earliest *int64 `json:"earliest,omitempty"`
	// A filter for tokens in the provided collect path and/or the events being collected
	Expression *string `json:"expression,omitempty"`
	// Maximum time the job is allowed to run (e.g., 30, 45s or 15m). Units are seconds, if not specified. Enter 0 for unlimited time.
	JobTimeout *string `json:"jobTimeout,omitempty"`
	// Latest time, for the given Range Timezone.
	Latest *int64 `json:"latest,omitempty"`
	// Level at which to set task logging.
	LogLevel *SavedJobCollectionScheduleRunSettingsLogLevel `json:"logLevel,omitempty"`
	// Max number of times a task can be rescheduled.
	MaxTaskReschedule *int64 `json:"maxTaskReschedule,omitempty"`
	// Limits the bundle size for files above the Lower task bundle size. E.g., bundle five 2MB files into one 10MB task bundle. Files greater than this size will be assigned to individual tasks.
	MaxTaskSize *string `json:"maxTaskSize,omitempty"`
	// Limits the bundle size for small tasks. E.g., bundle five 200KB files into one 1M task.
	MinTaskSize *string `json:"minTaskSize,omitempty"`
	// Job run mode. Preview will either return up to N matching results, or will run until capture time T is reached. Discovery will gather the list of files to turn into streaming tasks, without running the data collection job. Full Run will run the collection job.
	Mode *string `json:"mode,omitempty"`
	// Reschedule tasks that failed with non-fatal errors.
	RescheduleDroppedTasks *bool `json:"rescheduleDroppedTasks,omitempty"`
	// Time range for scheduled job.
	TimeRangeType *string `json:"timeRangeType,omitempty"`
	// Timezone to use for Earliest and Latest times (defaults to UTC).
	TimestampTimezone *string `json:"timestampTimezone,omitempty"`
}

func (o *SavedJobCollectionScheduleRunSettings) GetEarliest() *int64 {
	if o == nil {
		return nil
	}
	return o.Earliest
}

func (o *SavedJobCollectionScheduleRunSettings) GetExpression() *string {
	if o == nil {
		return nil
	}
	return o.Expression
}

func (o *SavedJobCollectionScheduleRunSettings) GetJobTimeout() *string {
	if o == nil {
		return nil
	}
	return o.JobTimeout
}

func (o *SavedJobCollectionScheduleRunSettings) GetLatest() *int64 {
	if o == nil {
		return nil
	}
	return o.Latest
}

func (o *SavedJobCollectionScheduleRunSettings) GetLogLevel() *SavedJobCollectionScheduleRunSettingsLogLevel {
	if o == nil {
		return nil
	}
	return o.LogLevel
}

func (o *SavedJobCollectionScheduleRunSettings) GetMaxTaskReschedule() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxTaskReschedule
}

func (o *SavedJobCollectionScheduleRunSettings) GetMaxTaskSize() *string {
	if o == nil {
		return nil
	}
	return o.MaxTaskSize
}

func (o *SavedJobCollectionScheduleRunSettings) GetMinTaskSize() *string {
	if o == nil {
		return nil
	}
	return o.MinTaskSize
}

func (o *SavedJobCollectionScheduleRunSettings) GetMode() *string {
	if o == nil {
		return nil
	}
	return o.Mode
}

func (o *SavedJobCollectionScheduleRunSettings) GetRescheduleDroppedTasks() *bool {
	if o == nil {
		return nil
	}
	return o.RescheduleDroppedTasks
}

func (o *SavedJobCollectionScheduleRunSettings) GetTimeRangeType() *string {
	if o == nil {
		return nil
	}
	return o.TimeRangeType
}

func (o *SavedJobCollectionScheduleRunSettings) GetTimestampTimezone() *string {
	if o == nil {
		return nil
	}
	return o.TimestampTimezone
}

// SavedJobCollectionSchedule - Configuration for a scheduled job.
type SavedJobCollectionSchedule struct {
	// A cron schedule on which to run this job.
	CronSchedule *string `json:"cronSchedule,omitempty"`
	// Determines whether or not this schedule is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// The maximum number of instances that may be running of this scheduled job at any given time.
	MaxConcurrentRuns *int64                                 `json:"maxConcurrentRuns,omitempty"`
	ResumeMissed      interface{}                            `json:"resumeMissed,omitempty"`
	Run               *SavedJobCollectionScheduleRunSettings `json:"run,omitempty"`
	// Skippable jobs can be delayed, up to their next run time, if the system is hitting concurrency limits.
	Skippable *bool `json:"skippable,omitempty"`
}

func (o *SavedJobCollectionSchedule) GetCronSchedule() *string {
	if o == nil {
		return nil
	}
	return o.CronSchedule
}

func (o *SavedJobCollectionSchedule) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *SavedJobCollectionSchedule) GetMaxConcurrentRuns() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxConcurrentRuns
}

func (o *SavedJobCollectionSchedule) GetResumeMissed() interface{} {
	if o == nil {
		return nil
	}
	return o.ResumeMissed
}

func (o *SavedJobCollectionSchedule) GetRun() *SavedJobCollectionScheduleRunSettings {
	if o == nil {
		return nil
	}
	return o.Run
}

func (o *SavedJobCollectionSchedule) GetSkippable() *bool {
	if o == nil {
		return nil
	}
	return o.Skippable
}

// SavedJobCollectionJobType - Job type.
type SavedJobCollectionJobType string

const (
	SavedJobCollectionJobTypeCollection      SavedJobCollectionJobType = "collection"
	SavedJobCollectionJobTypeExecutor        SavedJobCollectionJobType = "executor"
	SavedJobCollectionJobTypeScheduledSearch SavedJobCollectionJobType = "scheduledSearch"
)

func (e SavedJobCollectionJobType) ToPointer() *SavedJobCollectionJobType {
	return &e
}

func (e *SavedJobCollectionJobType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "collection":
		fallthrough
	case "executor":
		fallthrough
	case "scheduledSearch":
		*e = SavedJobCollectionJobType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SavedJobCollectionJobType: %v", v)
	}
}

type SavedJobCollection struct {
	Collector SavedJobCollectionCollector `json:"collector"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Unique ID for this Job.
	ID    *string                  `json:"id,omitempty"`
	Input *SavedJobCollectionInput `json:"input,omitempty"`
	// List of fields to remove from Discover results. Wildcards (e.g.: aws*) are allowed. This is useful when discovery returns sensitive fields that should not be exposed in the Jobs user interface.
	RemoveFields []string `json:"removeFields,omitempty"`
	// Resumes the ad hoc job if a failure condition causes Stream to restart during job execution.
	ResumeOnBoot *bool `json:"resumeOnBoot,omitempty"`
	// Configuration for a scheduled job.
	Schedule *SavedJobCollectionSchedule `json:"schedule,omitempty"`
	// Add tags for filtering and grouping in @{product}.
	Streamtags []string `json:"streamtags,omitempty"`
	// Time to keep the job's artifacts on disk after job completion. This also affects how long a job is listed in the Job Inspector.
	TTL *string `json:"ttl,omitempty"`
	// Job type.
	Type SavedJobCollectionJobType `json:"type"`
	// If enabled tasks are created and run by the same worker node.
	WorkerAffinity *bool `json:"workerAffinity,omitempty"`
}

func (o *SavedJobCollection) GetCollector() SavedJobCollectionCollector {
	if o == nil {
		return SavedJobCollectionCollector{}
	}
	return o.Collector
}

func (o *SavedJobCollection) GetEnvironment() *string {
	if o == nil {
		return nil
	}
	return o.Environment
}

func (o *SavedJobCollection) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *SavedJobCollection) GetInput() *SavedJobCollectionInput {
	if o == nil {
		return nil
	}
	return o.Input
}

func (o *SavedJobCollection) GetRemoveFields() []string {
	if o == nil {
		return nil
	}
	return o.RemoveFields
}

func (o *SavedJobCollection) GetResumeOnBoot() *bool {
	if o == nil {
		return nil
	}
	return o.ResumeOnBoot
}

func (o *SavedJobCollection) GetSchedule() *SavedJobCollectionSchedule {
	if o == nil {
		return nil
	}
	return o.Schedule
}

func (o *SavedJobCollection) GetStreamtags() []string {
	if o == nil {
		return nil
	}
	return o.Streamtags
}

func (o *SavedJobCollection) GetTTL() *string {
	if o == nil {
		return nil
	}
	return o.TTL
}

func (o *SavedJobCollection) GetType() SavedJobCollectionJobType {
	if o == nil {
		return SavedJobCollectionJobType("")
	}
	return o.Type
}

func (o *SavedJobCollection) GetWorkerAffinity() *bool {
	if o == nil {
		return nil
	}
	return o.WorkerAffinity
}
