// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Success - Authorization success
type Success struct {
	// Success message
	Message *string `json:"message,omitempty"`
}

func (o *Success) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
